name: Create new realease

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install fuse libfuse2
      run: sudo apt install fuse libfuse2

    - name: Make Syncthing AppDir
      run: |
        set -x
        version=$(grep -o "Syncthing:.*" README.md | cut -d ' ' -f2)
        echo "Syncthing version: $version"

        #rm -rf build/
        mkdir -p build/syncthing.AppDir/

        #cp syncthing.desktop build/syncthing.AppDir/

        cat > build/syncthing.AppDir/syncthing.desktop << 'EOF'
        [Desktop Entry]
        Type=Application
        Name=Syncthing
        Comment=E-Book Management
        Exec=syncthing %F
        Icon=syncthing
        MimeType=application/x-mobipocket-ebook;application/epub+zip;x-content/ebook-reader
        Categories=Office;Graphics;Viewer
        EOF

        chmod +x build/syncthing.AppDir/syncthing.desktop

        curl --location -o build/syncthing.AppDir/AppRun https://github.com/AppImage/AppImageKit/releases/download/continuous/AppRun-x86_64
        chmod +x build/syncthing.AppDir/AppRun

        mkdir -p build/syncthing.AppDir/usr/bin/
        cd build/syncthing.AppDir/usr/bin/

        curl -o - https://github.com/syncthing/syncthing/releases/download/v$version/syncthing-linux-amd64-v$version.tar.gz

        pwd
        ls -lah
        cd ../../../../
        pwd
        ls -lah

        cp build/syncthing.AppDir/usr/bin/resources/content-server/syncthing.png build/syncthing.AppDir
        cp README.md build/syncthing.AppDir

    - name: Get appimagetool
      run: |
        set -x
        #wget -q https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage
        #wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage

        version_go_appimage=$(wget -q -O - https://api.github.com/repos/probonopd/go-appimage/releases | grep "\"name.*appimagetool-.*-x86_64.AppImage\"" | head -n 1 | cut -d '-' -f2)
        echo "version_go_appimage: $version_go_appimage"

        wget -q "https://github.com/probonopd/go-appimage/releases/download/continuous/appimagetool-$version_go_appimage-x86_64.AppImage" -O appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage

    - name: Make AppImage
      run:  |
        set -x
        pwd; ls -lah
        version=$(grep -o "Syncthing:.*" README.md | cut -d ' ' -f2)
        echo "Syncthing version: $version"

        ARCH=x86_64 VERSION="${version}-1_JB" ./appimagetool-x86_64.AppImage build/calibre.AppDir

        fileName=$(ls Calibre*.AppImage)
        echo "fileName: $fileName"

        md5sum "$fileName" > "${fileName}.md5"
        pwd; ls -lah

    # Build - Errror: Resource not accessible by integration
    # Change Settings -> Actions -> General -> Workflow Permissions to allow read and write:
    # https://github.com/actions/first-interaction/issues/10#issuecomment-1506118886

    # https://github.com/marketplace/actions/upload-to-github-release
    - uses: xresloader/upload-to-github-release@main
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          file: "Syncthing*.AppImage; Syncthing*.zsync ; Syncthing*.md5"
          #delete_file: "random-name-*.txt;random-*.txt"
          release_id: ${{ steps.create_release.outputs.id }}
          #overwrite: true
          verbose: true
          #tags: true
          draft: false
          default_release_name: "Calibre V in AppImage"
